## Normalization problem

In [30]:
import numpy as np

# Create a random 5x5 ndarray
X = np.random.rand(5, 5)

# Normalize the array using the formula Z = (X - mean) / std
X_mean = X.mean()
X_std = X.std()
X_normalized = (X - X_mean) / X_std

# Save the normalized ndarray as 'X_normalized.npy'
np.save('X_normalized.npy', X_normalized)

# Print the array to see the result
print("Normalized Array:\n", X_normalized)

Normalized Array:
 [[ 1.36392002  0.42452654  1.03266149 -1.378528    1.09018092]
 [ 0.10818285 -1.37114775 -0.68673394  0.35676093 -1.89138546]
 [-0.15315414  0.23655741 -0.04034996  0.72117148 -1.61950912]
 [-0.03228547  0.67999943  1.08893866 -1.31605897  0.80261589]
 [ 1.42239826 -1.35907518  0.45906597 -0.8072338   0.86848195]]


## Divisible by 3 Problem

In [22]:
import numpy as np

# Create a 10x10 ndarray of the squares of the first 100 positive integers
A = np.arange(1, 101).reshape(10, 10) ** 2

# Filter out the elements that are divisible by 3
div_by_3 = A[A % 3 == 0]

# Save the result as 'div_by_3.npy'
np.save('div_by_3.npy', div_by_3)

# Print the array to see the result
print("Elements Divisible by 3:\n", div_by_3)

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
